#!/usr/bin/env bash
set -euo pipefail

#
# This checks the local secrets.conf file to see if it contains all secrets.
#


if [ ! -f secrets.conf ]; then echo "MISSING secrets.conf"; exit 1; fi

. secrets.conf

FAIL=0
for s in $(git grep -h get-secret | sed 's/^.*get-secret "\(.*\)".*/\1/' | sort)
do
  if [ -z "${SECRETS[$s]:-}" ]; then echo "MISSING $s"; FAIL=1; fi
done
if [ $FAIL != 0 ]; then exit -1; fi
